services:
  ipfs:
    container_name: ipfs
    image: ipfs/kubo:release
    environment:
      - IPFS_PATH=/data/ipfs
    volumes:
      - ./.data/ipfs:/data/ipfs
    # ports:
    #   - "4001:4001" # ipfs swarm
    #   - "5001:5001" # ipfs api
    #   - "8080:8080" # ipfs gateway
    restart: always
  
  postgres:
    container_name: postgres
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    
  web-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/src
    depends_on:
      - postgres
      - ipfs
    restart: always